spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  cloud:
    gateway:
      routes:
        - id: workshops-service
          uri: lb://workshops-service
          predicates:
            - Path=/api/workshop/**
          filters:
            - StripPrefix=2
        - id: visits-service
          uri: lb://visits-service
          predicates:
            - Path=/api/visit/**
          filters:
            - StripPrefix=2
        - id: costumers-service
          uri: lb://costumers-service
          predicates:
            - Path=/api/costumer/**
          filters:
            - StripPrefix=2



---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
